language: node_js
node_js:
  - 0.10
env:
  - ANGULAR_VERSION=1.2
  - ANGULAR_VERSION=1.3
  - ANGULAR_VERSION=1.4
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
before_script:
  - node scripts/travis/bower-versions
  - bower install
